### ISSUE TITLE
Can't get the script to show up

### ISSUE THREAD

**Issue by TayBZ27** [dcervenkov/mpmd_metadata#1]
This doesn't work for me.  I followed the instructions on cura 4.3 and 5.0 and it hasn't done anything. When I open up Cura log it tells me pyqt5 module isn't there.  What am I doing wrong?

**Comment by dcervenkov** [comment]
The title of the issue seems to hint that the script is not included in the Post Processing Scripts list, is that correct?

**Comment by Angelusz** [comment]
> The title of the issue seems to hint that the script is not included in the Post Processing Scripts list, is that correct?

I think that's what he means yes. I'm running into the same problem. I tried adding it to scripts in my installation folder and in the config folder under users, but neither lead to it showing up in the post processing scripts list. I can't find the cause. Thanks in advance!

**Comment by dcervenkov** [comment]
OK, should be fixed by 20ce141. Feel free to reopen the issue if you encounter it again.
