### ISSUE TITLE
With cura 5.1 the script not executed 

### ISSUE THREAD

**Issue by KenyeresTalpas** [dcervenkov/mpmd_metadata#2]
I try to use your script with cura 5.1 but didn't do anything.  Work fine with Cura 4.13.1 when I changed back the script to PyQt5.

**Comment by dcervenkov** [comment]
Turns out Cura 5 changed more things relevant for this script than just the PyQT version. Should be fixed by 41441d4de73a77c2b9affd8a089b1bb9348121bf. @KenyeresTalpas, can you confirm?

**Comment by KenyeresTalpas** [comment]
I can, yes it works fine now :) Thanks
